language: geberic
sudo: required
services:
  - docker

before_install:
  - docker build -t valdrin-1986/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true valdrin-1986/docker-react npm run test
